### ISSUE TITLE
th-abstraction-0.7 not accepted

### ISSUE THREAD

**Issue by ysangkok** [Happstack/boomerang#11]
I see this package is still maintained , as v1.4.9.2  was just published. Would it be possible to revise that release to accept the new th-abstraction?

See 

* https://github.com/commercialhaskell/stackage/issues/7352

**Comment by stepcut** [comment]
boomerang-1.4.9.3 is on hackage now.

**Comment by ysangkok** [comment]
Thank you Jeremy!
